name: enzo
favicon: null
layout_spectrum: 0.08888499578461051
typography_spectrum: 0.5738371692132205
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.03549221041612327
  lightness: 0.07761513045988977
  saturation: 0.2495863693766296
  rhythmicContrast: 0.8181136620696634
purpose: []
